<?php
$images = array(
    0 => '1',
    1 => '1',
    2 => '2',
    3 => '3',
    4 => '4',
    5 => '5',
    6 => '6',
    7 => '7',
    8 => '8',
    9 => '9',
    10 => '10',
    11 => '11',
);

$mots = array(
    0 => 'zozoter',
    1 => 'Lapin',
    2 => 'arizona',
    3 => 'araignee',
    4 => 'funambule',
    5 => 'elastique',
    6 => 'Parasol',
    7 => 'Vacances',
    8 => 'Amoureux',
    9 => 'saint-valentin',
    10 => 'agenda',
    11 => 'bicyclette',
    12 => 'paranormal',
    13 => 'armoire',
    14 => 'souris',
    15 => 'epouvantail',
    16 => 'aspirateur',
    17 => 'armurerie',
    18 => 'cotillons',
    19 => 'flibustier',
    20 => 'orchidoclaste',
    21 => 'apyretique',
    22 => 'amnesique',
    23 => 'mnemotechnique',
    24 => 'ludique',
    25 => 'yaourt',
    26 => 'facial',
);